name: Update Lottery Data

on:
  # Run every Monday at 9 AM UTC (1 AM PST / 2 AM PDT)
  schedule:
    - cron: '0 9 * * 1'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update lottery data
      run: npm run update:data
    
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet data/; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No data changes detected"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Data changes detected"
        fi
    
    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update lottery data'
        committer: GitHub Actions <actions@github.com>
        author: GitHub Actions <actions@github.com>
        branch: update-lottery-data
        delete-branch: true
        title: '🎰 Update Lottery Data'
        body: |
          ## Automated Lottery Data Update
          
          This PR updates the lottery CSV files with the latest data from BCLC (PlayNow.com).
          
          ### Updated Files:
          - `data/649.csv` - Lotto 6/49 historical data
          - `data/LOTTOMAX.csv` - Lotto Max historical data
          - `data/BC49.csv` - BC/49 historical data
          
          ### Data Source:
          All data is downloaded from official BCLC/PlayNow archives:
          - https://www.playnow.com/lottery/lotto-649-winning-numbers/
          - https://www.playnow.com/lottery/lotto-max-winning-numbers/
          - https://www.playnow.com/lottery/bc-49-winning-numbers/
          
          ---
          
          *This PR was automatically created by the Update Lottery Data workflow.*
          
          **Please review the changes and merge if they look correct!**
        labels: |
          automated
          data-update
    
    - name: Summary
      run: |
        if [ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]; then
          echo "✅ Lottery data updated and PR created"
        else
          echo "ℹ️  No changes in lottery data - already up to date"
        fi
